version: 2
updates:

  # Manage Github Actions versions.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "deps(ci):"
    labels:
      - c:deps

  # Manage Go package versions.
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "deps(go):"
    labels:
      - c:deps
    ignore:
      # Oasis dependencies are manually updated.
      - dependency-name: github.com/oasisprotocol/oasis-core/go
      - dependency-name: github.com/oasisprotocol/oasis-sdk/client-sdk/go
